openapi: 3.0.3
info:
  title: Erp
  description: Erp
  version: 1.0.0
paths:
  /finance:
    get:
      summary: Returns a list of finance.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    nominal:
                      type: integer
                      example: 10000
                    description:
                      type: string
                      example: "Selotip"
                    date:
                      type: string
                      example: "Selotip"
                    account:
                      type: integer
                      example: 201
    post:
      responses:
        201:


